ansible_user: ec2-user
ansible_password: DevOps321
PROJECT_NAME: robo
DOMAIN_NAME: mrmotam.online
INSTANCES:
- mongodb
- redis
- mysql
- rabbitMQ
- catalogue
- user
- cart
- shipping
- payment
- frontend
AMI_ID: ami-0220d79f3f480ecf5
INSTANCE_TYPE: t3.micro
METHOD: create
MONGODB_HOST: mongodb.mrmotam.online
REDIS_HOST: redis.mrmotam.online
MYSQL_HOST: mysql.mrmotam.online 
RABBITMQ_HOST: rabbitmq.mrmotam.online 
CATALOGUE_HOST: catalogue.mrmotam.online
USER_HOST: user.mrmotam.online
CART_HOST: cart.mrmotam.online
SHIPPING_HOST: shipping.mrmotam.online
PAYMENT_HOST: payment.mrmotam.online